version: '3.8'
services:
  dev-db:
    image: postgres:16
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest.js-db
    networks:
      - nest.js-api
networks:
  nest.js-api:
